var initializeculture =
{
    remove: 'Remove',
    update: 'Edit',
    add: 'Add',
    submit: 'Submit',
    close: 'Close',
    save: 'Save',
    SendComplete: 'Send Complete',
    cancel: "Cancel",
    ok: "Ok",
    notfindany: "Not Found",
    form_title: "New",
    new: "New",
    error: "Error",
    editform: "Edit",
    abbrevation: "en",
    areyousureyouwantlockthisitem: 'Are you sure, you want lock this item?',
    areyousureyouwantunlockthisitem: 'Are you sure, you want UnLock this item?',
    areyousureyouwantremovethisitem: 'Are you sure you want remove this item? ',
    areyousureyouwantpublishthisitem: 'Are you sure, you wante publish this item?',
    areyousureyouwantunpublishthisitem: 'Are you sure, you wante unpublish this item?',
    areyousureyouwantconfirmthisitem: 'Are you sure, you want confirm this item?',
    areyousureyouwantunconfirmthisitem: 'Are you sure, you want unconfirm this item?',
    areyousureyouwantsetdefaultlanguage: "Are you sure, you want set this item is default language?",
    RelatedArticle: 'Are you sure, you want related article ...',
    pleasewaite: 'Please wait...',
    edithasbeensuccessfully: "Edit item has been successfully.",
    newitemsuccessfully: "New Item successfully.",
    nomatchesfound: "No matches found",
    nodataavailableintable: 'No data available in table',
    areyousureyouwantremoveselecteditem :'Are you sure you want, remove all selected item?',
    publish: "Publish",
    unpublish: "UnPublish",
    remove_has_been_successfully: "حذف با موفقیت انجام شد",
    remove_not_successfully: "حذف با موفقیت انجام نشد",
    status_is_unknown: "وضعیت این درخواست تعیین نشده است.",
    are_you_sure_you_want_enable_this_item: "آیا مایل به فعال سازی این آیتم هستید؟",
    are_you_sure_you_want_disable_this_item: "آیا مایل به غیرفعال سازی این آیتم هستید؟",
    Username_Or_Password_Is_Not_Correct: "Username_Or_Password_Is_Not_Correct",
    This_Account_Has_Been_Locked_Out_Please_Try_Again_Later: "This_Account_Has_Been_Locked_Out_Please_Try_Again_Later",
    Authorize_Has_Been_Successfully: "Authorize_Has_Been_Successfully",
    Please_Check_Your_Email_To_Reset_Your_Password: "ایمیل خود را جهت بازیابی رمز عبور برسی کنید."
}